name: pokemon_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: 0.12.0+2
  provider: 3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/pokemons.json
    - assets/moves.json
    

